name: Run Laravel Watch FTP

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy config file
        run: cp ./example.config.json ./config.json

      - name: Run script
        run: npm run watch


        env: 
            NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
